// <auto-generated />
using System;
using CovidLAMap.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CovidLAMap.Data.Migrations
{
    [DbContext(typeof(CovidDbContext))]
    partial class CovidDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:postgis", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CovidLAMap.Core.Models.RegisteredCredential", b =>
                {
                    b.Property<string>("HashId")
                        .HasColumnType("text");

                    b.Property<string>("CitizenAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("CredentialCreation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CredintialType")
                        .HasColumnType("integer");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(POINT, 4326)");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SubjectHashId")
                        .HasColumnType("text");

                    b.HasKey("HashId");

                    b.ToTable("RegisteredCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
