CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE "Countries" (
    gid integer NOT NULL DEFAULT (nextval('countries_gid_seq'::regclass)),
    featurecla character varying(15) NULL,
    scalerank smallint NULL,
    labelrank smallint NULL,
    sovereignt character varying(32) NULL,
    sov_a3 character varying(3) NULL,
    adm0_dif smallint NULL,
    level smallint NULL,
    type character varying(17) NULL,
    admin character varying(36) NULL,
    adm0_a3 character varying(3) NULL,
    geou_dif smallint NULL,
    geounit character varying(36) NULL,
    gu_a3 character varying(3) NULL,
    su_dif smallint NULL,
    subunit character varying(36) NULL,
    su_a3 character varying(3) NULL,
    brk_diff smallint NULL,
    name character varying(25) NULL,
    name_long character varying(36) NULL,
    brk_a3 character varying(3) NULL,
    brk_name character varying(32) NULL,
    brk_group character varying(17) NULL,
    abbrev character varying(13) NULL,
    postal character varying(4) NULL,
    formal_en character varying(52) NULL,
    formal_fr character varying(35) NULL,
    name_ciawf character varying(45) NULL,
    note_adm0 character varying(22) NULL,
    note_brk character varying(63) NULL,
    name_sort character varying(36) NULL,
    name_alt character varying(19) NULL,
    mapcolor7 smallint NULL,
    mapcolor8 smallint NULL,
    mapcolor9 smallint NULL,
    mapcolor13 smallint NULL,
    pop_est numeric(10,0) NULL,
    pop_rank smallint NULL,
    gdp_md_est double precision NULL,
    pop_year smallint NULL,
    lastcensus smallint NULL,
    gdp_year smallint NULL,
    economy character varying(26) NULL,
    income_grp character varying(23) NULL,
    wikipedia smallint NULL,
    fips_10_ character varying(3) NULL,
    iso_a2 character varying(3) NULL,
    iso_a3 character varying(3) NULL,
    iso_a3_eh character varying(3) NULL,
    iso_n3 character varying(3) NULL,
    un_a3 character varying(4) NULL,
    wb_a2 character varying(3) NULL,
    wb_a3 character varying(3) NULL,
    woe_id integer NULL,
    woe_id_eh integer NULL,
    woe_note character varying(167) NULL,
    adm0_a3_is character varying(3) NULL,
    adm0_a3_us character varying(3) NULL,
    adm0_a3_un smallint NULL,
    adm0_a3_wb smallint NULL,
    continent character varying(23) NULL,
    region_un character varying(23) NULL,
    subregion character varying(25) NULL,
    region_wb character varying(26) NULL,
    name_len smallint NULL,
    long_len smallint NULL,
    abbrev_len smallint NULL,
    tiny smallint NULL,
    homepart smallint NULL,
    min_zoom double precision NULL,
    min_label double precision NULL,
    max_label double precision NULL,
    ne_id numeric(10,0) NULL,
    wikidataid character varying(8) NULL,
    name_ar character varying(72) NULL,
    name_bn character varying(148) NULL,
    name_de character varying(46) NULL,
    name_en character varying(44) NULL,
    name_es character varying(44) NULL,
    name_fr character varying(54) NULL,
    name_el character varying(88) NULL,
    name_hi character varying(126) NULL,
    name_hu character varying(52) NULL,
    name_id character varying(46) NULL,
    name_it character varying(48) NULL,
    name_ja character varying(63) NULL,
    name_ko character varying(47) NULL,
    name_nl character varying(49) NULL,
    name_pl character varying(47) NULL,
    name_pt character varying(43) NULL,
    name_ru character varying(86) NULL,
    name_sv character varying(57) NULL,
    name_tr character varying(42) NULL,
    name_vi character varying(56) NULL,
    name_zh character varying(36) NULL,
    geom geometry(MultiPolygon) NULL,
    centroid geometry NULL,
    CONSTRAINT countries_pkey PRIMARY KEY (gid)
);

CREATE TABLE "EthEvents" (
    "Id" text NOT NULL,
    "Name" text NULL,
    "FilterId" text NULL,
    "NodeName" text NULL,
    "TransactionHash" text NULL,
    "LogIndex" integer NOT NULL,
    "BlockNumber" integer NOT NULL,
    "BlockHash" text NULL,
    "Address" text NULL,
    "Status" text NULL,
    "EventSpecificationSignature" text NULL,
    "NetworkName" text NULL,
    "FailedTimes" integer NOT NULL,
    CONSTRAINT "PK_EthEvents" PRIMARY KEY ("Id")
);

CREATE TABLE "States" (
    gid integer NOT NULL DEFAULT (nextval('ne_10m_admin_1_states_provinces_gid_seq'::regclass)),
    featurecla character varying(20) NULL,
    scalerank smallint NULL,
    adm1_code character varying(9) NULL,
    diss_me integer NULL,
    iso_3166_2 character varying(8) NULL,
    wikipedia character varying(84) NULL,
    iso_a2 character varying(2) NULL,
    adm0_sr smallint NULL,
    name character varying(44) NULL,
    name_alt character varying(129) NULL,
    name_local character varying(66) NULL,
    type character varying(38) NULL,
    type_en character varying(27) NULL,
    code_local character varying(5) NULL,
    code_hasc character varying(8) NULL,
    note character varying(114) NULL,
    hasc_maybe character varying(13) NULL,
    region character varying(43) NULL,
    region_cod character varying(15) NULL,
    provnum_ne integer NULL,
    gadm_level smallint NULL,
    check_me smallint NULL,
    datarank smallint NULL,
    abbrev character varying(9) NULL,
    postal character varying(3) NULL,
    area_sqkm smallint NULL,
    sameascity smallint NULL,
    labelrank smallint NULL,
    name_len smallint NULL,
    mapcolor9 smallint NULL,
    mapcolor13 smallint NULL,
    fips character varying(5) NULL,
    fips_alt character varying(9) NULL,
    woe_id integer NULL,
    woe_label character varying(64) NULL,
    woe_name character varying(44) NULL,
    latitude double precision NULL,
    longitude double precision NULL,
    sov_a3 character varying(3) NULL,
    adm0_a3 character varying(3) NULL,
    adm0_label smallint NULL,
    admin character varying(36) NULL,
    geonunit character varying(40) NULL,
    gu_a3 character varying(3) NULL,
    gn_id integer NULL,
    gn_name character varying(72) NULL,
    gns_id integer NULL,
    gns_name character varying(80) NULL,
    gn_level smallint NULL,
    gn_region character varying(1) NULL,
    gn_a1_code character varying(10) NULL,
    region_sub character varying(41) NULL,
    sub_code character varying(5) NULL,
    gns_level smallint NULL,
    gns_lang character varying(3) NULL,
    gns_adm1 character varying(4) NULL,
    gns_region character varying(4) NULL,
    min_label double precision NULL,
    max_label double precision NULL,
    min_zoom double precision NULL,
    wikidataid character varying(9) NULL,
    name_ar character varying(85) NULL,
    name_bn character varying(128) NULL,
    name_de character varying(51) NULL,
    name_en character varying(47) NULL,
    name_es character varying(52) NULL,
    name_fr character varying(52) NULL,
    name_el character varying(82) NULL,
    name_hi character varying(134) NULL,
    name_hu character varying(41) NULL,
    name_id character varying(45) NULL,
    name_it character varying(49) NULL,
    name_ja character varying(93) NULL,
    name_ko character varying(58) NULL,
    name_nl character varying(44) NULL,
    name_pl character varying(45) NULL,
    name_pt character varying(43) NULL,
    name_ru character varying(91) NULL,
    name_sv character varying(48) NULL,
    name_tr character varying(44) NULL,
    name_vi character varying(49) NULL,
    name_zh character varying(61) NULL,
    ne_id bigint NULL,
    geom geometry(MultiPolygon) NULL,
    centroid geometry NULL,
    CONSTRAINT ne_10m_admin_1_states_provinces_pkey PRIMARY KEY (gid)
);

CREATE TABLE "EthValueDTO" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Type" text NULL,
    "Value" text NULL,
    "EthEventDTOId" text NULL,
    "EthEventDTOId1" text NULL,
    CONSTRAINT "PK_EthValueDTO" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EthValueDTO_EthEvents_EthEventDTOId" FOREIGN KEY ("EthEventDTOId") REFERENCES "EthEvents" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_EthValueDTO_EthEvents_EthEventDTOId1" FOREIGN KEY ("EthEventDTOId1") REFERENCES "EthEvents" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "RegisteredCredentials" (
    "HashId" text NOT NULL,
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "CitizenAddress" text NULL,
    "SubjectHashId" text NOT NULL,
    "StartDate" timestamp without time zone NOT NULL,
    "CredentialCreation" timestamp without time zone NOT NULL,
    "Sex" integer NOT NULL,
    "Location" geometry(Point) NULL,
    "Lat" double precision NOT NULL,
    "Lon" double precision NOT NULL,
    "CredentialType" integer NOT NULL,
    "Reason" integer NOT NULL,
    "IsRevoked" boolean NOT NULL,
    "Age" smallint NOT NULL,
    "HasNoSymptoms" boolean NULL,
    "HasSymptoms" boolean NULL,
    "HasFever" boolean NULL,
    "HasCought" boolean NULL,
    "HasBreathingIssues" boolean NULL,
    "HasLossSmell" boolean NULL,
    "HasHeadache" boolean NULL,
    "HasMusclePain" boolean NULL,
    "HasSoreThroat" boolean NULL,
    "CountryGId" integer NOT NULL,
    "StateGId" integer NOT NULL,
    CONSTRAINT "PK_RegisteredCredentials" PRIMARY KEY ("HashId"),
    CONSTRAINT "InCountry" FOREIGN KEY ("CountryGId") REFERENCES "Countries" (gid) ON DELETE RESTRICT,
    CONSTRAINT "InState" FOREIGN KEY ("StateGId") REFERENCES "States" (gid) ON DELETE RESTRICT
);

CREATE INDEX countries_geom_idx ON "Countries" USING gist (geom);

CREATE INDEX "IX_EthValueDTO_EthEventDTOId" ON "EthValueDTO" ("EthEventDTOId");

CREATE INDEX "IX_EthValueDTO_EthEventDTOId1" ON "EthValueDTO" ("EthEventDTOId1");

CREATE INDEX "fki_InCountry" ON "RegisteredCredentials" ("CountryGId");

CREATE INDEX "fki_InState" ON "RegisteredCredentials" ("StateGId");

CREATE INDEX "SubjectIdIdx" ON "RegisteredCredentials" ("IsRevoked", "SubjectHashId" varchar_ops COLLATE "C.UTF-8");

CREATE INDEX ne_10m_admin_1_states_provinces_geom_idx ON "States" USING gist (geom);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200427021612_InitialModel', '3.1.3');

